name: Juice Shop Security Pipeline

on:
  push:
    branches: [ "master", "main" ] # Kod buraya yüklendiğinde çalışır

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Gitleaks: Şifre sızıntısı var mı?
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true 

      # 2. Semgrep: Kodda hata/zafiyet var mı?
      - name: Semgrep SAST
        run: |
          python3 -m pip install semgrep
          semgrep scan --config auto
        continue-on-error: true

      # 3. Docker Build: Uygulamayı paketle
      - name: Build Docker Image
        run: docker build -t juice-shop-image .

      # 4. Syft: İçindeki kütüphanelerin listesini çıkar (SBOM)
      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: juice-shop-image
          artifact-name: sbom.json

      # 5. Docker Hub'a Gönder (Az önce oluşturduğunuz Secretlar burada kullanılıyor)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag juice-shop-image ${{ secrets.DOCKERHUB_USERNAME }}/owasp-juice-shop:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/owasp-juice-shop:latest
